# Generated by Django 3.2.4 on 2021-06-11 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bill_order', '0002_auto_20210610_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
