# Generated by Django 3.2.4 on 2021-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='photo',
            field=models.ImageField(default='soup.jpeg', upload_to=''),
        ),
    ]
